CREATE DATABASE test;

CREATE TABLE `USER` (
	`num` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'pk',
	`id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'id' COLLATE 'utf8mb4_general_ci',
	`pw` VARCHAR(50) NULL DEFAULT NULL COMMENT 'pw' COLLATE 'utf8mb4_general_ci',
	`name` VARCHAR(50) NULL DEFAULT NULL COMMENT 'name' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`num`) USING BTREE
)
COMMENT='유저테이블'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
