CREATE TABLE `USER` (
	`num` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'pk',
	`id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'id',
	`pw` VARCHAR(50) NULL DEFAULT NULL COMMENT 'pw',
	`name` VARCHAR(50) NULL DEFAULT NULL COMMENT 'name',
	PRIMARY KEY (`num`)
);